// Run with: bun scripts/generate-models.ts > pkg/ai/models_generated.go
import { MODELS } from "../../pi-mono/packages/ai/src/models.generated.js";

let go = `// Code generated by scripts/generate-models.ts. DO NOT EDIT.
// Ported from: packages/ai/src/models.generated.ts
// Upstream hash: 1caadb2e
package ai

// generatedModels contains all built-in model definitions.
var generatedModels = []*Model{
`;

for (const [provider, models] of Object.entries(MODELS)) {
	for (const [id, model] of Object.entries(models as Record<string, any>)) {
		const inputTypes = model.input.map((i: string) => {
			if (i === "text") return "InputText";
			if (i === "image") return "InputImage";
			return `"${i}"`;
		}).join(", ");
		let headers = "";
		if (model.headers) {
			const entries = Object.entries(model.headers)
				.map(([k, v]) => `"${k}": "${v}"`)
				.join(", ");
			headers = `\t\tHeaders: map[string]string{${entries}},\n`;
		}
		go += `\t{
\t\tID:            ${JSON.stringify(model.id)},
\t\tName:          ${JSON.stringify(model.name)},
\t\tApi:           ${JSON.stringify(model.api)},
\t\tProvider:      ${JSON.stringify(model.provider)},
\t\tBaseURL:       ${JSON.stringify(model.baseUrl)},
\t\tReasoning:     ${model.reasoning},
\t\tInput:         []InputModality{${inputTypes}},
\t\tCost:          ModelCost{Input: ${model.cost.input}, Output: ${model.cost.output}, CacheRead: ${model.cost.cacheRead}, CacheWrite: ${model.cost.cacheWrite}},
\t\tContextWindow: ${model.contextWindow},
\t\tMaxTokens:     ${model.maxTokens},
${headers}\t},
`;
	}
}

go += `}
`;

process.stdout.write(go);
