#!/bin/bash
# Converts models.generated.ts to models_generated.go
# Usage: ./scripts/generate-models.sh ../pi-mono/packages/ai/src/models.generated.ts > pkg/ai/models_generated.go

set -euo pipefail

INPUT="${1:-../pi-mono/packages/ai/src/models.generated.ts}"

if [ ! -f "$INPUT" ]; then
    echo "Error: $INPUT not found" >&2
    exit 1
fi

# Use node/bun to parse the TS and output Go
cat <<'SCRIPT' | node - "$INPUT"
const fs = require('fs');
const input = fs.readFileSync(process.argv[2], 'utf8');

// Extract the MODELS object by evaluating a simplified version
// Remove TypeScript-specific syntax
let cleaned = input
    .replace(/import type.*$/gm, '')
    .replace(/export const MODELS = /, 'const MODELS = ')
    .replace(/\} satisfies Model<[^>]+>/g, '}')
    .replace(/} as const;/, '};');

// Evaluate to get the data
const MODELS = eval('(' + cleaned.replace('const MODELS = ', '') + ')');

// Generate Go
let go = `// Code generated by scripts/generate-models.sh. DO NOT EDIT.
// Ported from: packages/ai/src/models.generated.ts
// Upstream hash: 1caadb2e
package ai

// generatedModels contains all built-in model definitions.
var generatedModels = []*Model{
`;

for (const [provider, models] of Object.entries(MODELS)) {
    for (const [id, model] of Object.entries(models)) {
        const inputTypes = model.input.map(i => `"${i}"`).join(', ');
        let compat = '';
        if (model.compat) {
            compat = `\t\tCompat: nil, // TODO: serialize compat\n`;
        }
        let headers = '';
        if (model.headers) {
            const entries = Object.entries(model.headers).map(([k,v]) => `"${k}": "${v}"`).join(', ');
            headers = `\t\tHeaders: map[string]string{${entries}},\n`;
        }
        go += `\t{
\t\tID:            ${JSON.stringify(model.id)},
\t\tName:          ${JSON.stringify(model.name)},
\t\tApi:           ${JSON.stringify(model.api)},
\t\tProvider:      ${JSON.stringify(model.provider)},
\t\tBaseURL:       ${JSON.stringify(model.baseUrl)},
\t\tReasoning:     ${model.reasoning},
\t\tInput:         []string{${inputTypes}},
\t\tCost:          ModelCost{Input: ${model.cost.input}, Output: ${model.cost.output}, CacheRead: ${model.cost.cacheRead}, CacheWrite: ${model.cost.cacheWrite}},
\t\tContextWindow: ${model.contextWindow},
\t\tMaxTokens:     ${model.maxTokens},
${headers}${compat}\t},
`;
    }
}

go += `}
`;

process.stdout.write(go);
SCRIPT
