package main

import (
	"os"
	"strings"
	"testing"
)

// The Homebrew formula users actually get is generated by GoReleaser from the
// caveats: block in .goreleaser.yaml; homebrew/fir.rb.template is a reference
// copy. They are easy to drift apart because nothing in the build reads the
// template. This test pins them together.

const (
	goreleaserPath = "../../.goreleaser.yaml"
	templatePath   = "../../homebrew/fir.rb.template"
)

// caveatsFromGoreleaser returns the body of the first `caveats: |` block,
// dedented by its own indentation.
func caveatsFromGoreleaser(t *testing.T) string {
	t.Helper()
	data, err := os.ReadFile(goreleaserPath)
	if err != nil {
		t.Fatalf("read %s: %v", goreleaserPath, err)
	}
	lines := strings.Split(string(data), "\n")
	for i, line := range lines {
		if strings.TrimSpace(line) != "caveats: |" {
			continue
		}
		keyIndent := len(line) - len(strings.TrimLeft(line, " "))
		var body []string
		for _, next := range lines[i+1:] {
			if strings.TrimSpace(next) == "" {
				body = append(body, "")
				continue
			}
			indent := len(next) - len(strings.TrimLeft(next, " "))
			if indent <= keyIndent {
				break
			}
			body = append(body, next[keyIndent+2:])
		}
		return strings.Join(body, "\n")
	}
	t.Fatalf("no `caveats: |` block found in %s", goreleaserPath)
	return ""
}

// caveatsFromTemplate returns the heredoc body of the template's def caveats.
func caveatsFromTemplate(t *testing.T) string {
	t.Helper()
	data, err := os.ReadFile(templatePath)
	if err != nil {
		t.Fatalf("read %s: %v", templatePath, err)
	}
	lines := strings.Split(string(data), "\n")
	start := -1
	for i, line := range lines {
		if strings.TrimSpace(line) == "<<~EOS" {
			start = i + 1
			break
		}
	}
	if start < 0 {
		t.Fatalf("no heredoc opener found in %s", templatePath)
	}
	var body []string
	for _, line := range lines[start:] {
		if strings.TrimSpace(line) == "EOS" {
			return strings.Join(body, "\n")
		}
		body = append(body, strings.TrimPrefix(line, "      "))
	}
	t.Fatalf("unterminated heredoc in %s", templatePath)
	return ""
}

func TestHomebrewCaveatsTemplateMatchesGoreleaser(t *testing.T) {
	fromConfig := strings.TrimRight(caveatsFromGoreleaser(t), "\n")
	fromTemplate := strings.TrimRight(caveatsFromTemplate(t), "\n")
	if fromConfig != fromTemplate {
		t.Errorf("homebrew/fir.rb.template caveats drifted from .goreleaser.yaml\n--- goreleaser ---\n%s\n--- template ---\n%s", fromConfig, fromTemplate)
	}
}

func TestHomebrewCaveatsStaysHeredocSafe(t *testing.T) {
	body := caveatsFromGoreleaser(t)
	if body == "" {
		t.Fatal("caveats block is empty")
	}
	for i, line := range strings.Split(body, "\n") {
		// GoReleaser drops each line into a <<~EOS heredoc, so a bare EOS
		// would close it early; {{ would be eaten by its templating.
		if strings.TrimSpace(line) == "EOS" {
			t.Errorf("line %d is a bare EOS and would terminate the heredoc", i+1)
		}
		if strings.Contains(line, "{{") {
			t.Errorf("line %d contains {{, which GoReleaser would treat as a template action: %q", i+1, line)
		}
	}
}
